# Generated by Django 5.0.7 on 2024-07-31 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='api.status'),
        ),
    ]
