# Generated by Django 5.0.7 on 2024-08-02 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_couponcategory_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payments',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
