# Generated by Django 5.0.7 on 2024-08-02 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_address_active_payments_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='name',
            field=models.CharField(default='', max_length=120),
        ),
    ]
