# Generated by Django 5.1 on 2024-09-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_order_coupon_order_restaurant_alter_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwd_change_link',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
